### ISSUE TITLE
Add `for_each` to repeat actions for a list of values

### ISSUE THREAD

**Issue by drevell** [abcxyz/abc#127]
### TL;DR

As a template author, I want to be able to run the same set of actions repeatedly for each element of a list. For example, I might have a list of "environments" and I want to create a subdirectory for each environment containing some files.

One idea of how this might work:

```
input:
  - name: 'environments'
    desc: 'a comma-separated list of environments, e.g. staging,prod'

steps:
  - action: 'for'
    params:
      each:  'split(input.environments, ",")'  # a CEL expression that outputs a list
      as: 'environment'  # Adds a new variable "{{.environment}}" into the go-template context
      sub_steps:
        - action: 'include'
          params:
            paths: ['main.tf']
            as: ['{{.environment}}/main.tf']

        # more per-environment actions go here

# After the "for" action, execution resumes without the {{.environment}}
```

Or, if we don't want to use CEL:

```
input:
  - name: 'environments'
    desc: 'a comma-separated list of environments, e.g. staging,prod'

steps:
  - action: 'for'
    params:
      each: '{{.environments}}'
      var_name: 'environment'
      split_char: ','
      sub_steps:
        - action: 'include'
          params:
            paths: ['main.tf']
            as: ['{{.environment}}/main.tf']

```

cc @verbanicm @pdewilde @kevya-google
