### ISSUE TITLE
Make paths accept objects

### ISSUE THREAD

**Issue by sethvargo** [abcxyz/abc#130]
I'm worried about accepting multiple values as an array instead of an array of a concrete type:

```yaml
paths: ['a', 'b']
```

versus

```yaml
paths:
  - path: 'a'
  - path: 'b'
```

The second is more verbose, but gives us flexibility in the future to add control values in the future:

```yaml
paths:
  - path: 'a'
    banana: 'apple'
  - path: 'b'
```

This has come up a few times as we try to add additional options to control how a particular file behaves in the list.

**Comment by drevell** [comment]
cc @kevya-google, this may be an alternative API for skip-if-exists behavior

**Comment by drevell** [comment]
There's also the possibility of accepting both options in the parser. The user could choose between:

```
- paths: ['a.txt']
```

... and ...
```
- paths:
  - path: a.txt 
```

They'd choose the first one for conciseness, and the second one for fine-grained configuration of each path.

Downsides: complexity of code and documentation; users might be confused by having two ways to do it.

@sethvargo WDYT?

**Comment by sethvargo** [comment]
It's definitely possible; we'd have to decode into `any` and then use something like `mapstructure` to get it into the proper Go types, but it's definitely possible. I think my biggest concern is that, the moment you need to customize _one_ file, you now have to break the entire list out (unless we have the paths be a crazy union type of `[]string | struct`, so you could do:

```yaml
paths:
  - 'a.txt'
  - 'b.txt'
  - path: 'c.txt'
    only_if: 'today.is_tuesday'
```

But honestly that feels even worse to me...

**Comment by kevya-google** [comment]
Do multiple includes work?
```
paths: ['a', 'b'] # no options
paths: ['c', 'd'] # apply option 1 to c and d only
    apply_option_1: true
paths: ['d', 'e', 'f'] # apply option 2 to d, e, f
    apply_option_2: true
paths: ['g']
    apply_option_3: true
```
Or is this too messy?

**Comment by sethvargo** [comment]
No, but paths could be a slice:

```yaml
paths:
  - paths: ['a', 'b']
    only_if: 'banana'
  - paths: ['c', 'd']
    notify: 'kitchen'
```

It's pretty similar to what I proposed above, but allows for multiple files to be specified instead of a single one.
