### ISSUE TITLE
Conditional execution of steps with `if`

### ISSUE THREAD

**Issue by drevell** [abcxyz/abc#220]
### TL;DR

We could add the ability to conditionally execute one or more template steps using a CEL predicate.

+ @verbanicm 

### Detailed design

```markdown
There are two possibilities we can think of for how this might work. There could be an `if` field on every action, or there could be a new action type `if`.

Design 1: an `if` field on every action


inputs:
  - name: 'include_auth0'

steps:
  - action: 'include'
    if: 'bool(include_auth0)'
    desc: 'conditionally include auth0 integration'
    params: 
      paths: ['auth0']
```

Design 2: a new action type for `if` that has a list of steps:

```
inputs:
  - name: 'include_auth0'

steps:
 - action: `if`
   params:
     then:
       - action: 'include'
          expr: 'bool(include_auth0)'
          desc: 'conditionally include auth0 integration'
          params: 
            paths: ['auth0']
```
```


### Alternatives considered

_No response_

### Additional information

_No response_
