### ISSUE TITLE
Inputs that are conditionally skipped

### ISSUE THREAD

**Issue by drevell** [abcxyz/abc#289]
### TL;DR

Sometimes, one input is unnecessary, depending on the value of another input. For example, you might have two inputs `use_postgres`, and `postgres_config_file`; if `use_postgres` is false then you don't care about `postgres_config_file`.

One way this could look: we could add a CEL expression `skip_if` to each input. For example:

```
inputs:
  - name: use_postgres
  - name: postgres_config_file
    skip_if: '!bool(use_postgres)'
```
