### ISSUE TITLE
Skip does not skip the current included path

### ISSUE THREAD

**Issue by sqin2019** [abcxyz/abc#323]
### TL;DR

Below action does not skip main.go, to skip main.go, it needs to be '.'.
```
    action: 'include'
    params:
      paths: ['main.go']
      skip: ['main.go']
```

### Expected behavior

"main.go" should be skipped, skip should be able to skip the included path itself.

### Observed behavior

"main.go" not skipped.

### Environment Details

```markdown
I am using examples/templates/render/hello_jupiter/spec.yaml
```
