### ISSUE TITLE
Allow validation to be independent of any input

### ISSUE THREAD

**Issue by drevell** [abcxyz/abc#357]
### TL;DR

Currently, template authors can enforce valid inputs by putting a `rules` field on an input declaration in spec.yaml. We should add another way of doing validation that isn't tied to any particular input declaration.

Suppose there's a template that must be installed from git because it uses the `_git_sha` or `_git_tag` built-in template variables. Template authors need to be able to fail the render operation with an error message if the template isn't being rendered from a git repo.

One way this could look:

```
api_version: 'cli.abcxyz.dev/v1alpha1'
kind: 'Template'
desc: 'A template that must be installed from git'

inputs:
- name: 'whatever'
  desc: 'whatever'
  # This already exists: validation for a particular rule
  rules:
  - rule: 'int(whatever) > 42'
    message: 'the value of whatever must be greater than 42'


# New proposal: a list of rules that aren't attached to any input
rules:
- rule: '_git_tag != ""'
  message: 'this template must be rendered from a git tag, e.g. `abc templates render github.com/foo/bar@v1.2.3`'
```
