### ISSUE TITLE
Support renaming/relocating in `include` action

### ISSUE THREAD

**Issue by drevell** [abcxyz/abc#37]
### TL;DR

Currently, the `include` action takes a file or directory from the template and places it in the scratch directory *at the same location*. Users will likely want to place files/directories at varying locations. For example:

```
- action: 'include'
  params:
    - paths: ['foo_example/handlers.go', 'foo_example/configdir]

    # The following is the new proposed feature:
    - replace_prefix:   
      - from: 'foo_example'
      - to: 'my_app'
```
