### ISSUE TITLE
Support optional inputs with defaults

### ISSUE THREAD

**Issue by drevell** [abcxyz/abc#40]
### TL;DR

Currently, if the user doesn't provide a value for every input, the template won't render. Instead, we could have the spec.yaml declare an input as optional and provide a default value.

```
inputs:
  - name: 'concurrent_workers'
    required: false  # default is true
    default: '10' # must be a YAML string, because this is a string replacement tool, hence the quotes
    desc: 'the number of worker threads'
    
```

There is some existing code for this that declares a "required" field in the YAML, but the logic isn't implemented yet; Required" is useless without "default": https://github.com/abcxyz/abc/blob/c0122ffb6bd49d4c123e184539a22f9fa0b6559f/templates/model/spec.go#L128
